/* Init.hpp - Configuration initialisation for description.ext. - vigil.vindex@gmail.com - https://creativecommons.org/licenses/by-sa/4.0/ */
#include "Modules.hpp"
#include "Params.hpp"
#include "Config.hpp"
#include "Briefing.hpp"
#include "Functions.hpp"
#include "GC.hpp"
#include "Gear.hpp"
#include "HUD.hpp"
#include "Music.hpp"
#include "Orbat.hpp"
#include "Radio.hpp"
#include "RE.hpp"
#include "Respawn.hpp"
#include "Revive.hpp"
#include "Sounds.hpp"
#include "Tasks.hpp"
#include "Titles.hpp"
#include "Unit.hpp"
class CfgCommunicationMenu {}; // http://community.bistudio.com/wiki/Arma_3_Communication_Menu
class CfgNotifications {}; // https://community.bistudio.com/wiki/Notification