// [[-30,985]] call VVM_fnc_orbatMarker;
private ["_position","_xPos","yPos"];
_position = _this select 0;
_xPos = _position select 0;
_yPos = _position select 1;
[[[_xPos,_yPos],[_xPos,_yPos - 500],[_xPos - 500,_yPos - 500],[_xPos - 500,_yPos],[_xPos,_yPos]],10,["ColorWhite",1]] call VVM_fnc_lineToMapGlobal;
[[_xPos - 460,_yPos - 30],[0,1],  [" ORBAT - CALLSIGN - RADIO ","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 60],[0,1],  [" ","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 90],[0,1],  ["CO         LR 0, SR 0","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 120],[0,1], ["JTAC       LR 1, SR 0","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 150],[0,1], ["ALPHA SL   LR 0, SR 1","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 180],[0,1], ["ALPHA      SR 1","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 210],[0,1], ["BRAVO SL   LR 0, SR 2","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 240],[0,1], ["BRAVO      SR 2","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 270],[0,1], ["CHARLIE SL  LR 0, SR 3","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 300],[0,1], ["CHARLIE     SR 3","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 330],[0,1], ["DELTA SL   LR 0, SR 4","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 360],[0,1], ["DELTA      SR 4","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 390],[0,1], ["ECHO SL    LR 0, SR 5","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 420],[0,1], ["ECHO       SR 5","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 450],[0,1], ["EAGLE      LR 1","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
[[_xPos - 460,_yPos - 480],[0,1], ["HAWK       LR 1","ColorWhite",1]] call VVM_fnc_textToMapGlobal;
